---
version: '2'
services:
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:5.3.0
    links:
      - elasticsearch
    ports:
      - 5601:5601

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    cap_add:
      - IPC_LOCK
    volumes:
      - ./elasticsearch/config:/usr/share/elasticsearch/config
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:5.3.0
    links:
      - elasticsearch
    environment:
      - PWD
    volumes:
      - ./examples:/examples
    ports:
      - 9600:9600

volumes:
  esdata1:
    driver: local
